= Spoke Pipelines
The Pipeline for Deploying ACM Spokes using Tektoncd

== Pre-requsites

Configure your cloud accounts as detailed in the following docs:

* https://docs.openshift.com/container-platform/4.4/installing/installing_aws/installing-aws-account.html[Amazon]

* https://docs.openshift.com/container-platform/4.4/installing/installing_azure/installing-azure-account.html#installing-azure-account[Azure]

* https://docs.openshift.com/container-platform/4.4/installing/installing_gcp/installing-gcp-account.html[Google]

* Install Advanced Cluster Management(ACM) in  one of your clusters

=== Create Cloud Secrets

[NOTE]
=====
The following section is one time setup, the resources will be reused in all the spoke cluster deployments.
=====

Create the Cloud credentials secret that will be used by the spoke dpeloyment:

==== Amazon

Create a secret with the following keys and its value corresponding to you Amazon account

* aws_access_key_id
* aws_secret_access_key

(e.g.)
[source,bash]
----
oc create secret generic -n demos my-aws-creds \
  --from-literal=aws_access_key_id=<your aws acces key> \
  --from-literal=aws_secret_access_key=<your aws secret key>
----

==== Azure

Create a secret with the following keys and its value corresponding to you Azure account

* baseDomainresourceGroup
* osServicePrincipal.json

(e.g.)
[source,bash]
----
oc create secret generic -n demos my-azr-creds \
  --from-file=osServicePrincipal.json=<the Service Principal json file> \
  --from-literal=baseDomainresourceGroup=<your base domain resource group>
----

==== Google

Create a secret with the following keys and its value corresponding to you Google account

* project_id
* osServiceAccount.json

(e.g.)
[source,bash]
----
oc create secret generic -n demos my-gcp-creds \
  --from-file=osServiceAccount.json=<the gcp serviceaccount json file> \
  --from-literal=project_id=<your gcp project id to be used>
----

=== Create OpenShift Pull Secret secret

Create a secret to hold the OpenShift pull secret, if you dont have pull scret try getting one from https://try.openshfit.com[try.openshift.com]. The secret should have key called `pullSecret` with the contents from your pull secret file:

e.g.
[source,bash]
----
oc create secret generic -n demos ocp-pull-secret \
  --from-file=pullSecret=< your openshift pull secret file> 
----

=== Pipelines

The spoke provisioning is done using Tekton Pipelines.

==== Create Pipelines Project

All the pipelines and its related resources will be deployed in this project, run

[source,bash]
----
export NAMESPACE=<your-namespace>
kubectl create namespace $NAMESPACE
----

[IMPORTANT]
====
Update the kustomization.yaml **namespace** to match your namespace i.e. `$NAMESPACE`
====

==== Create PVC, Tasks, Pipelines and Cloud extravars secret

The link:./env/extravars.example[extravars] is used to configre settings for the cloud that will be used during provisioning. Run the following command to create the PVC, Tasks, Pipelines.

IMPORTANT: Please make the note of the name of the secret generated as it will be needed during the Pipeline run command later.

[source,bash]
----
oc apply --kustomize $PWD
----

==== Define cluster-admin Role Binding to `spoke-pipeline-admin`

[source,bash]
----
oc create clusterrolebinding \
  spoke-secrets-to-pipeline \
  --clusterrole=cluster-admin \
  --serviceaccount=$NAMESPACE:spoke-pipeline-admin
----

==== Run the sample pipeline

Run the following sample pipeline to deploy the cluster to Google Cloud

[source,bash]
----
tkn pipeline start spoke-deploy-cluster \
    --serviceaccount=spoke-pipeline-admin \
    --param=cluster-name=my-dev \
    --param git-url=https://github.com/kameshsampath/spoke-pipelines \
    --param git-revision=wip \
    --workspace name=extra-vars,secret=<your secret name>,item=extravars=extravars \
    --workspace name=git-source,claimName=spoke-source \
    --showlog
----

Wait :coffee for the cluster to be ready.