apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ansible-runner
spec:
  workspaces:
    - name: source
    - name: extravars
  steps:
    - name: copy-extravars
      image: registry.access.redhat.com/ubi8/ubi-minimal
      script: |-
        #!/bin/sh
        cp -av $(workspaces.extravars.path)/extravars $(workspaces.source.path)/env/extravars
    - name: gen-spoke-resources
      image: docker.io/ansible/ansible-runner:latest
      command:
        - ansible-runner
      env:
        - name: RUNNER_PLAYBOOK
          value: generate-spoke-resources.yaml
        - name: PROJECT_DIR
          value: "$(workspaces.source.path)/project"
      args:
        - -p
        - generate-spoke-resources.yaml
        - run
        - "$(workspaces.source.path)"
