apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ansible-runner
spec:
  params:
    - name: cloud
      description: The cloud to provision the spoke into
    - name: spoke-configmap
      description: The ConfigMap with values of extravars that need to be used
  workspaces:
    - name: source
  steps:
    - name: gen-spoke-resources
      image: docker.io/ansible/ansible-runner:latest
      command:
        - ansible-runner
      env:
        - name: RUNNER_PLAYBOOK
          value: generate-spoke-resources.yaml
        - name: PROJECT_DIR
          value: "$(workspaces.source.path)/project"
      volumes:
        - name: extravars
          mountPath: "$(workspaces.source.path)/env"
      args:
        - -p
        - generate-spoke-resources.yaml
        - run
        - "$(workspaces.source.path)"
  volumes:
    - name: extravars
      configMap:
        name: "$(params.spoke-configmap)"
