apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ansible-runner
spec:
  workspaces:
    - name: source
    - name: extravars
  steps:
    - name: copy-extravars
      image: registry.access.redhat.com/ubi8/ubi-minimal
      script: |-
        #!/bin/sh
        cp -av $(workspaces.extravars.path)/extravars $(workspaces.source.path)/env/extravars
    - name: gen-spoke-resources
      image: quay.io/kameshsampath/ansible-runner:latest
      imagePullPolicy: Always
      args:
        - ansible-runner
        - -p
        - generate-spoke-resources.yaml
        - run
        - "$(workspaces.source.path)"
