apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: spoke-deploy-cluster-
spec:
  pipelineRef:
    name: spoke-deploy-cluster
  workspaces:
    - name: extra-vars
      configMap:
        name: extravars-gcp
        items:
          - key: extravars
            path: extravars
    - name: git-source
      persistentVolumeClaim:
        claimName: spoke-source
  params:
    - name: git-url
      value: https://github.com/kameshsampath/spoke-pipelines
    - name: git-revision
      value: wip
