apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: spoke-deploy-cluster-
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: spoke-deploy-cluster
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: spoke-source
    - name: extra-vars
      secret:
        secretName: extravars-gcp
        items:
          - key: extravars
            path: extravars
  params:
    - name: git-url
      value: https://github.com/kameshsampath/spoke-pipelines
    - name: git-revision
      value: wip
    - name: cluster-name
      value: my-dev
