apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: spoke-deploy-cluster
spec:
  params:
    - name: git-url
    - name: git-revision
  workspaces:
    - name: git-source
    - name: extra-vars
  tasks:
    - name: fetch-from-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        # TODO move as parameter
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: git-source
    - name: generate-spoke-resources
      taskRef:
        name: ansible-runner
      runAfter:
        - fetch-from-git
      workspaces:
        - name: source
          workspace: git-source
        - name: extravars
          workspace: extra-vars
