apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spoke-source
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
