---
- name: Get Amazon Secrets
  set_fact:
    azure_secrets: "{{ lookup('k8s', api_version='v1',kind='Secret',namespace=cloud_credentials_secret.namespace,resource_name=cloud_credentials_secret.name) }}"

- name: Set Amazon Cloud Facts
  set_fact:
    aws_access_key_id: "{{azure_secrets.data.aws_access_key_id | b64decode}}"
    aws_secret_access_key: "{{azure_secrets.data.aws_secret_access_key | b64decode}}"

