---
- name: Get OCP Secrets
  set_fact:
    gcp_secrets: "{{ lookup('k8s', api_version='v1',kind='Secret',namespace=openshift_pull_secret.namespace,resource_name=openshift_pull_secret.name) }}"

- name: Create OCP Pull Secret Json
  copy:
    dest: "{{spoke_out_dir}}/.dockerconfigjson"
    content: "{{ gcp_secrets.data.pullSecret | b64decode }}"
    group: '0'
    mode: g+w